---
- name: create systemd service unit
  template:
    src: yace_exporter.service.j2
    dest: /etc/systemd/system/yace_exporter.service
    owner: "{{ yace_exporter_system_user }}"
    group: "{{ yace_exporter_system_group }}"
    mode: 0644
  notify:
    - restart yace exporter

- name: configure yace exporter
  template:
    src: yace_exporter.yml.j2
    dest: /etc/yace_exporter.yml
    owner: "{{ yace_exporter_system_user }}"
    group: "{{ yace_exporter_system_group }}"
    mode: 0644
  notify:
    - reload yace exporter
