---
- include: install.yml
  become: true
  tags:
    - yace_exporter_install

- include: configure.yml
  become: true
  tags:
    - yace_exporter_configure

- name: ensure yace_exporter service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: yace_exporter
    state: started
    enabled: true
  tags:
    - yace_exporter_run
