---
- name: restart yace exporter
  become: true
  systemd:
    daemon_reload: true
    name: yace_exporter
    state: restarted

- name: reload yace exporter
  become: true
  systemd:
    name: yace_exporter
    state: reloaded
